/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Class`;

DROP TABLE IF EXISTS `Student`;

CREATE TABLE `Student` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `num` BIGINT UNSIGNED NOT NULL,
  `name` TEXT NOT NULL,
  `age` SMALLINT UNSIGNED NULL,
  `classId` BIGINT UNSIGNED NOT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `num_i`
  ON `Student` (`num`);

CREATE INDEX `classId_i`
  ON `Student` (`classId`);

CREATE TABLE `Class` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `className` TEXT NOT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `className_i`
  ON `Class` (`className`);

